In [42]:
import pandas as pd

print("Pandas is working!")
print(pd.__version__)

Pandas is working!
2.3.3

In [43]:
import os

print(os.listdir("../dataset"))

['Car_Price_Prediction.csv.xlsx']

In [44]:
import pandas as pd

df = pd.read_excel("../dataset/Car_Price_Prediction.csv.xlsx")

df.head()

,Make,Model,Year,Engine Size,Mileage,Fuel Type,Transmission,Price
0,Honda,Model B,2015,3.9,74176,Petrol,Manual,30246.207931
1,Ford,Model C,2014,1.7,94799,Electric,Automatic,22785.747684
2,BMW,Model B,2006,4.1,98385,Electric,Manual,25760.290347
3,Honda,Model B,2015,2.6,88919,Electric,Automatic,25638.003491
4,Honda,Model C,2004,3.4,138482,Petrol,Automatic,21021.386657

In [45]:
print(df.shape)
print(df.dtypes)
print(df.isnull().sum())

(1000, 8)
Make             object
Model            object
Year              int64
Engine Size     float64
Mileage           int64
Fuel Type        object
Transmission     object
Price           float64
dtype: object
Make            0
Model           0
Year            0
Engine Size     0
Mileage         0
Fuel Type       0
Transmission    0
Price           0
dtype: int64

In [46]:
df.head()

,Make,Model,Year,Engine Size,Mileage,Fuel Type,Transmission,Price
0,Honda,Model B,2015,3.9,74176,Petrol,Manual,30246.207931
1,Ford,Model C,2014,1.7,94799,Electric,Automatic,22785.747684
2,BMW,Model B,2006,4.1,98385,Electric,Manual,25760.290347
3,Honda,Model B,2015,2.6,88919,Electric,Automatic,25638.003491
4,Honda,Model C,2004,3.4,138482,Petrol,Automatic,21021.386657

In [47]:
df.shape

(1000, 8)

In [48]:
df.isnull().sum()

Make            0
Model           0
Year            0
Engine Size     0
Mileage         0
Fuel Type       0
Transmission    0
Price           0
dtype: int64

In [49]:
df.dtypes

Make             object
Model            object
Year              int64
Engine Size     float64
Mileage           int64
Fuel Type        object
Transmission     object
Price           float64
dtype: object

In [50]:
X = df.drop("Price", axis=1)
y = df["Price"]

In [51]:
X = pd.get_dummies(
    X,
    columns=["Make", "Model", "Fuel Type", "Transmission"],
    drop_first=True
)

In [52]:
X.head()

,Year,Engine Size,Mileage,Make_BMW,Make_Ford,Make_Honda,Make_Toyota,Model_Model B,Model_Model C,Model_Model D,Model_Model E,Fuel Type_Electric,Fuel Type_Petrol,Transmission_Manual
0,2015,3.9,74176,False,False,True,False,True,False,False,False,False,True,True
1,2014,1.7,94799,False,True,False,False,False,True,False,False,True,False,False
2,2006,4.1,98385,True,False,False,False,True,False,False,False,True,False,True
3,2015,2.6,88919,False,False,True,False,True,False,False,False,True,False,False
4,2004,3.4,138482,False,False,True,False,False,True,False,False,False,True,False

In [53]:
import sklearn
print(sklearn.__version__)

1.6.1

In [54]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [55]:
# Target
y = df["Price"]

# Features
X = df.drop("Price", axis=1)

# One-Hot Encoding
X = pd.get_dummies(
    X,
    columns=["Make", "Model", "Fuel Type", "Transmission"],
    drop_first=True
)

# Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [56]:
from sklearn.linear_model import LinearRegression

In [57]:
model = LinearRegression()

In [58]:
model.fit(X_train, y_train)

LinearRegression()

In [59]:
y_pred = model.predict(X_test)

In [60]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error :", mae)
print("Mean Squared Error  :", mse)
print("Root Mean Squared Error :", rmse)
print("R2 Score :", r2)

Mean Absolute Error : 1810.5547575776739
Mean Squared Error  : 5005471.209263081
Root Mean Squared Error : 2237.2910425921523
R2 Score : 0.8170961815662858

In [61]:
from sklearn.ensemble import RandomForestRegressor

In [62]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

In [63]:
rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [64]:
rf_pred = rf_model.predict(X_test)

In [65]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

rf_mae = mean_absolute_error(y_test, rf_pred)
rf_mse = mean_squared_error(y_test, rf_pred)
rf_rmse = np.sqrt(rf_mse)
rf_r2 = r2_score(y_test, rf_pred)

print("Random Forest Results")
print("---------------------")
print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R2  :", rf_r2)

Random Forest Results
---------------------
MAE : 1941.9830211598298
RMSE: 2389.9730299206667
R2  : 0.791280125621917

In [66]:
import pandas as pd

results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest"],
    "MAE": [mae, rf_mae],
    "RMSE": [rmse, rf_rmse],
    "R2 Score": [r2, rf_r2]
})

results

               Model          MAE         RMSE  R2 Score
0  Linear Regression  1810.554758  2237.291043  0.817096
1      Random Forest  1941.983021  2389.973030  0.791280

In [67]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\nikhil\onedrive\desktop\car-price-prediction\.venv\lib\site-packages (2.1.4)
Requirement already satisfied: numpy in c:\users\nikhil\onedrive\desktop\car-price-prediction\.venv\lib\site-packages (from xgboost) (2.0.2)
Requirement already satisfied: scipy in c:\users\nikhil\onedrive\desktop\car-price-prediction\.venv\lib\site-packages (from xgboost) (1.13.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\Nikhil\OneDrive\Desktop\car-price-prediction\.venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [68]:
from xgboost import XGBRegressor

In [69]:
xgb_model = XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

In [70]:
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=200, n_jobs=None,
             num_parallel_tree=None, random_state=42, ...)

In [71]:
xgb_pred = xgb_model.predict(X_test)

In [72]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

xgb_mae = mean_absolute_error(y_test, xgb_pred)
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_pred))
xgb_r2 = r2_score(y_test, xgb_pred)

print("MAE :", xgb_mae)
print("RMSE:", xgb_rmse)
print("R2  :", xgb_r2)

MAE : 2080.384454149137
RMSE: 2575.0953833661843
R2  : 0.7576938456207009

In [73]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest", "XGBoost"],
    "MAE": [mae, rf_mae, xgb_mae],
    "RMSE": [rmse, rf_rmse, xgb_rmse],
    "R2 Score": [r2, rf_r2, xgb_r2]
})

results

               Model          MAE         RMSE  R2 Score
0  Linear Regression  1810.554758  2237.291043  0.817096
1      Random Forest  1941.983021  2389.973030  0.791280
2            XGBoost  2080.384454  2575.095383  0.757694

In [74]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=500,
    max_depth=20,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

In [75]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

rf_mae = mean_absolute_error(y_test, rf_pred)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
rf_r2 = r2_score(y_test, rf_pred)

print("MAE :", rf_mae)
print("RMSE:", rf_rmse)
print("R2  :", rf_r2)

MAE : 1905.5892570605456
RMSE: 2349.33779942684
R2  : 0.7983172580687141

In [76]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model.coef_
})

importance.sort_values(by="Importance", key=abs, ascending=False)

                Feature   Importance
1           Engine Size  1968.237084
0                  Year   518.304810
9         Model_Model D   310.769080
10        Model_Model E  -266.084077
5            Make_Honda  -135.643103
4             Make_Ford   122.462235
3              Make_BMW    94.745403
11   Fuel Type_Electric   -83.722784
8         Model_Model C   -78.331858
7         Model_Model B   -44.541570
13  Transmission_Manual    37.938605
6           Make_Toyota    32.766893
12     Fuel Type_Petrol    17.318774
2               Mileage    -0.048835

In [77]:
import joblib

joblib.dump(model, "car_price_model.pkl")

['car_price_model.pkl']

In [78]:
import os

print(os.getcwd())
print(os.path.abspath("car_price_model.pkl"))
print(os.path.getsize("car_price_model.pkl"))

c:\Users\Nikhil\OneDrive\Desktop\car-price-prediction\notebook
c:\Users\Nikhil\OneDrive\Desktop\car-price-prediction\notebook\car_price_model.pkl
1225

In [79]:
import joblib

joblib.dump(model, "../backend/car_price_model.pkl")

print("Model saved successfully in backend folder!")

Model saved successfully in backend folder!

In [80]:
import os

path = "../backend/car_price_model.pkl"

print("File exists:", os.path.exists(path))
print("File size:", os.path.getsize(path), "bytes")

File exists: True
File size: 1225 bytes

In [81]:
import os

model_path = "../backend/car_price_model.pkl"
encoder_path = "../backend/encoder_columns.pkl"

print("Model exists:", os.path.exists(model_path))
print("Model size:", os.path.getsize(model_path), "bytes")

print("Encoder exists:", os.path.exists(encoder_path))
print("Encoder size:", os.path.getsize(encoder_path), "bytes")

Model exists: True
Model size: 1225 bytes
Encoder exists: True
Encoder size: 0 bytes

In [82]:
print(type(X))
print(X.shape)
print(X.columns.tolist()[:10])

<class 'pandas.core.frame.DataFrame'>
(1000, 14)
['Year', 'Engine Size', 'Mileage', 'Make_BMW', 'Make_Ford', 'Make_Honda', 'Make_Toyota', 'Model_Model B', 'Model_Model C', 'Model_Model D']

In [83]:
print(type(X_train))
print(X_train.shape)
print(X_train.columns.tolist()[:10])

<class 'pandas.core.frame.DataFrame'>
(800, 14)
['Year', 'Engine Size', 'Mileage', 'Make_BMW', 'Make_Ford', 'Make_Honda', 'Make_Toyota', 'Model_Model B', 'Model_Model C', 'Model_Model D']

In [84]:
import joblib
import os

# Save model
joblib.dump(model, "../backend/car_price_model.pkl")

# Save feature column names
joblib.dump(list(X_train.columns), "../backend/encoder_columns.pkl")

print("Model size:", os.path.getsize("../backend/car_price_model.pkl"))
print("Encoder size:", os.path.getsize("../backend/encoder_columns.pkl"))

Model size: 1225
Encoder size: 223